### ISSUE TITLE
Add main.py to uPyEasy to call upyeasy.main() automatically on startup

### ISSUE THREAD

**Issue by Andrew49** [letscontrolit/uPyEasy#1]
Currently, (in Alpha v53) it's necessary to type in "import upyeasy, upyeasy.main()" or to manually download a main.py file to carry out these commands and initiate startup of uPyEasy. Include these in the frozen code so it happens automatically.

**Comment by Lisa999** [comment]
This should be solved in V54, boot.py should do the import and run the main function.
