### ISSUE TITLE
Jump to Scripts, after clicking add in Rules

### ISSUE THREAD

**Issue by berbergh** [letscontrolit/uPyEasy#11]
When I click Add in the Rules section, upyEasy opens a window in Scripts.
Herunder a sequence: Go to Rules, Add, close in Scripts and back ik Rules again.

`stack: 2000 out of 15360
GC: total: 96000, used: 79840, free: 16160
 No. of 1-blocks: 1264, 2-blocks: 157, max blk sz: 901, max free sz: 162
570881462.097 <HTTPRequest object at 3ffbd890> <StreamWriter <socket>> "GET /rules"
2018-02-02 10:10:44 [debug] uPyEasy-uPyEasy: Pages: Authorize User!?
2018-02-02 10:10:44 [debug] uPyEasy-uPyEasy: Pages: Display Rules Page
2018-02-02 10:10:44 [debug] uPyEasy-uPyEasy: Utils: uPyEasy Name
stack: 2000 out of 15360
GC: total: 96000, used: 77376, free: 18624
 No. of 1-blocks: 1216, 2-blocks: 152, max blk sz: 901, max free sz: 140
570881462.097 <HTTPRequest object at 3ffbb5e0> <StreamWriter <socket>> "GET /static/upyeasy.css"
stack: 2000 out of 15360
GC: total: 96000, used: 78928, free: 17072
 No. of 1-blocks: 1261, 2-blocks: 159, max blk sz: 901, max free sz: 140
570881462.097 <HTTPRequest object at 3ffc2460> <StreamWriter <socket>> "GET /static/upyeasy.js"
static/upyeasy.css
static/upyeasy.js
stack: 2000 out of 15360
GC: total: 96000, used: 89776, free: 6224
 No. of 1-blocks: 1439, 2-blocks: 185, max blk sz: 901, max free sz: 140
570881462.097 <HTTPRequest object at 3ffc8650> <StreamWriter <socket>> "GET /rule_setting?oper=add"
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Pages: Authorize User!?
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Pages: Entering rule Settings Page
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Pages: GET
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: oper
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Pages: Oper: add
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Pages: Add rule
2018-02-02 10:10:52 [debug] uPyEasy-uPyEasy: Utils: uPyEasy Name
stack: 2000 out of 15360
GC: total: 96000, used: 77456, free: 18544
 No. of 1-blocks: 1221, 2-blocks: 149, max blk sz: 901, max free sz: 163
570881462.097 <HTTPRequest object at 3ffbd7d0> <StreamWriter <socket>> "GET /static/upyeasy.css"
stack: 2000 out of 15360
GC: total: 96000, used: 79008, free: 16992
 No. of 1-blocks: 1266, 2-blocks: 156, max blk sz: 901, max free sz: 163
570881462.097 <HTTPRequest object at 3ffc44c0> <StreamWriter <socket>> "GET /static/upyeasy.js"
static/upyeasy.css
static/upyeasy.js
stack: 2000 out of 15360
GC: total: 96000, used: 89952, free: 6048
 No. of 1-blocks: 1444, 2-blocks: 178, max blk sz: 901, max free sz: 148
570881462.097 <HTTPRequest object at 3ffc88c0> <StreamWriter <socket>> "GET /rules"
2018-02-02 10:10:59 [debug] uPyEasy-uPyEasy: Pages: Authorize User!?
2018-02-02 10:10:59 [debug] uPyEasy-uPyEasy: Pages: Display Rules Page
2018-02-02 10:10:59 [debug] uPyEasy-uPyEasy: Utils: uPyEasy Name
stack: 2000 out of 15360
GC: total: 96000, used: 77392, free: 18608
 No. of 1-blocks: 1216, 2-blocks: 151, max blk sz: 901, max free sz: 163
570881462.097 <HTTPRequest object at 3ffbcde0> <StreamWriter <socket>> "GET /static/upyeasy.css"
stack: 2000 out of 15360
GC: total: 96000, used: 78944, free: 17056
 No. of 1-blocks: 1261, 2-blocks: 158, max blk sz: 901, max free sz: 163
570881462.097 <HTTPRequest object at 3ffc3330> <StreamWriter <socket>> "GET /static/upyeasy.js"
static/upyeasy.css
static/upyeasy.js

`

**Comment by Lisa999** [comment]
Fixed in v0.2.1
