### ISSUE TITLE
Decimals field not saved, and doesn't control value display (DB18b20, BME280 plugins)

### ISSUE THREAD

**Issue by Andrew49** [letscontrolit/uPyEasy#3]
The "decimals" fields in these 2 plugins don't seem to work as expected. When setting a value, e.g. 1, some unrelated values (phone numbers) are shown in the dropdown. If a value is entered, it doesn't seem to be saved - it has gone if we go back into the plugin a second time. And the displayed values in the main Devices page still have an arbitrary and variable number of decimal places.

**Comment by Lisa999** [comment]
The cause of this bug lies in issue #15 and will be fixed there.
